const { Sequelize } = require('../db');
const { sequelize } = require('../db');

const MagicItem = sequelize.define('magicItem', {
  name: Sequelize.TEXT,
  aura: Sequelize.TEXT,
  cl: Sequelize.TEXT,
  slot: Sequelize.TEXT,
  price: Sequelize.TEXT,
  weight: Sequelize.TEXT,
  description: Sequelize.TEXT,
  requirements: Sequelize.TEXT,
  cost: Sequelize.TEXT,
  group: Sequelize.TEXT,
  source: Sequelize.TEXT,
  al: Sequelize.TEXT,
  int: Sequelize.TEXT,
  wis: Sequelize.TEXT,
  cha: Sequelize.TEXT,
  ego: Sequelize.TEXT,
  communication: Sequelize.TEXT,
  senses: Sequelize.TEXT,
  powers: Sequelize.TEXT,
  magicItems: Sequelize.TEXT,
  fullText: Sequelize.TEXT,
  destruction: Sequelize.TEXT,
  minorArtifactFlag: Sequelize.BOOLEAN,
  majorArtifactFlag: Sequelize.BOOLEAN,
  abjuration: Sequelize.BOOLEAN,
  conjuration: Sequelize.BOOLEAN,
  divination: Sequelize.BOOLEAN,
  enchantment: Sequelize.BOOLEAN,
  evocation: Sequelize.BOOLEAN,
  necromancy: Sequelize.BOOLEAN,
  transmutation: Sequelize.TEXT,
  auraStrength: Sequelize.TEXT,
  weightValue: Sequelize.TEXT,
  priceValue: Sequelize.INTEGER,
  costValue: Sequelize.INTEGER,
  languages: Sequelize.TEXT,
  baseItem: Sequelize.TEXT,
  linkText: Sequelize.TEXT,
  mythic: Sequelize.BOOLEAN,
  legendaryWeapon: Sequelize.BOOLEAN,
  illusion: Sequelize.BOOLEAN,
  universal: Sequelize.BOOLEAN,
  scaling: Sequelize.TEXT,
  isIntelligentItem: Sequelize.BOOLEAN,
});

module.exports = MagicItem;